######################## default configuration ####################
baseURL = "https://www.dmanalytic.com"
title = "DM Analytic"
theme = "educenter-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "DM Analytic" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = ["fr"] # desable language from here


############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "Brindamos capacitación en el uso de programas y en estadística aplicada a: economía, finanzas, riesgos, segmentación de mercados, proyección de series de tiempo, modelos de predicción y modelos de probabilidad."
author = "Danny Moreno"
# contact info
address = "Quito - Ecuador"
mobile = "+593986854964"
email = "dmanalytic.info@gmail.com"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # your id
# top header
top_header = true

# Preloader
[params.preloader]
enable = false
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = false
# mailchimp subsciption
link = "https://forms.gle/KVrfAG5i8R1xhvtb8" # replace this url with yours

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png" # marker size 37*55 px

# cookies
[params.cookies]
enable = false
expire_days = 2
  
############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/DM-Analytic-108437811087739"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/dmanalytic"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "https://www.instagram.com/dmanalytic"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/company/dmanalytic"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# copyright
copyright = "Developed by: Danny Moreno"



################### English navigation ####################

# main menu
[[Languages.en.menu.main]]
name = "Nosotros"
url = "about"
weight = 1

[[Languages.en.menu.main]]
name = "Cursos"
url = "course"
weight = 2

[[Languages.en.menu.main]]
weight = 3
name = "Eventos"
url = "event"

[[Languages.en.menu.main]]
name = "Blog"
url = "blog"
weight = 4
  
[[Languages.en.menu.main]]
name = "Contacto"
url = "contact"
weight = 5


# footer menu

[[Languages.en.menu.footer]]
name = "Profesores"
url = "teacher"


################################### French language #####################################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
home = "Accueil"
# copyright
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"



################### French navigation ####################

# main menu
[[Languages.fr.menu.main]]
name = "À propos"
url = "about"
weight = 1

[[Languages.fr.menu.main]]
name = "Cours"
url = "course"
weight = 2

[[Languages.fr.menu.main]]
weight = 3
name = "Pages"
hasChildren = true

  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "teacher"
  url = "teacher"

  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "notice"
  url = "notice"

  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "Évènement"
  url = "event"

  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "Cursus"
  url = "scholarship"

  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "research"
  url = "research"
  
[[Languages.fr.menu.main]]
name = "blog"
url = "blog"
weight = 4
  
[[Languages.fr.menu.main]]
name = "Contact"
url = "contact"
weight = 5


# footer menu

[[Languages.fr.menu.footer]]
name = "Eventos"
url = "event"